repos:
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.15.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
