name: release
on:
  pull_request:
    branches:
      - main
    types: [closed]
permissions:
  contents: write
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Check version
        run: |
          version=$(cz -nr 21 bump --get-next)
          echo "version=${version}" >> $GITHUB_ENV
      - name: Bump version
        if: env.version != ''
        run: |-
          cz bump
          git push
