name: Release
on:
  pull_request:
    branches:
      - main
    types: [closed]
permissions:
  contents: write
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Check version
        run: |
          version=$(uv run cz -nr 21 bump --get-next)
          echo "version=${version}" >> $GITHUB_ENV
      - name: Bump version
        if: env.version != ''
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          uv run cz bump
          git remote remove origin
          git remote add origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com:asyncfast/amgi.git
          git push
